export class ComponentTypeFull {
    public type	: string;
    public storageVersion	: string;
    public activeStatus	: string;
    public adminModified	: boolean;
    public createDts	: Date;
    public createUser	: string;
    public updateDts	: Date;
    public updateUser	: string;
    public allowOnSubmission	: boolean;
    public componentType	: string;
    public dataEntryAttributes	: boolean;
    public dataEntryContacts	: boolean;
    public dataEntryMedia	: boolean;
    public dataEntryQuestions	: boolean;
    public dataEntryRelationships	: boolean;
    public dataEntryResources	: boolean;
    public dataEntryReviews	: boolean;
    public description	: string;
    public label	: string;
    public parentComponentType	: string;
}